CREATE TABLE IF NOT EXISTS guests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nickname VARCHAR(255) NOT NULL,
  comment VARCHAR(500) NOT NULL,
  created_at DATETIME NOT NULL,
  delete_token VARCHAR(36) NOT NULL UNIQUE,
  view_count BIGINT NOT NULL DEFAULT 0
);
