name: CI/CD to AWS Elastic Beanstalk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository so the runner gets your code.
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      # Cache your Maven repository to speed up builds.
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      # Build your Spring Boot application.
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Install the Elastic Beanstalk CLI.
      - name: Install AWS EB CLI
        run: pip install awsebcli --upgrade

      # Configure AWS credentials for deployment.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy your application to Elastic Beanstalk.
      - name: Deploy to AWS Elastic Beanstalk
        env:
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
        run:
          # Deploy to your environment.
          eb deploy $EB_ENVIRONMENT_NAME --region ${{ secrets.AWS_REGION }}
