name: CI/CD to AWS Elastic Beanstalk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp target/guestbook-0.1.0-SNAPSHOT.jar deploy/
          # Create a Procfile if needed
          echo "web: java -jar guestbook-0.1.0-SNAPSHOT.jar" > deploy/Procfile
          cd deploy && zip -r ../deploy.zip .

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          region: ${{ secrets.REGION }}
          version_label: "guestbook-${{ github.run_number }}-${{ github.sha }}"
          deployment_package: deploy.zip
